apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ionir-fs-ext4-16k-24h
provisioner: ionir
volumeBindingMode: Immediate
reclaimPolicy: Delete
parameters:
  type: ext4
  blockSize: 16k
  historyPolicy: 24hourshistory
