apiVersion: v1
kind: Service
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  type: LoadBalancer
  ports:
    - port: 1433
      targetPort: 1433
      protocol: TCP
  selector:
    app: mssql
