apiVersion: crd.ionir.com/v1
kind: HistoryPolicy
metadata:
  name: 1-hour-history
  namespace: ionir
spec:
  daysGranularityRetention: ""
  hoursGranularityRetention: ""
  minutesGranularityRetention: ""
  monthsGranularityRetention: ""
  policyName: 1-hour-history
  secondsGranularityRetention: 1h