apiVersion: volume.ionir.com/v1
kind: HistoryPolicy
metadata:
  name: 1-hour-history
  namespace: ionir
spec:
  daysGranularityRetention: ""
  hoursGranularityRetention: ""
  minutesGranularityRetention: ""
  monthsGranularityRetention: ""
  policyName: 1-hour-history
  secondsGranularityRetention: 1h
---
apiVersion: volume.ionir.com/v1
kind: HistoryPolicy
metadata:
  name: 6-hour-history
  namespace: ionir
spec:
  daysGranularityRetention: ""
  hoursGranularityRetention: ""
  minutesGranularityRetention: ""
  monthsGranularityRetention: ""
  policyName: 6-hour-history
  secondsGranularityRetention: 6h
---
apiVersion: volume.ionir.com/v1
kind: HistoryPolicy
metadata:
  name: 24-hour-history
  namespace: ionir
spec:
  daysGranularityRetention: ""
  hoursGranularityRetention: ""
  minutesGranularityRetention: ""
  monthsGranularityRetention: ""
  policyName: 24-hour-history
  secondsGranularityRetention: 24h
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ionir-postgres
parameters:
  blockSize: 16k
  type: ext4
provisioner: ionir
reclaimPolicy: Retain
volumeBindingMode: Immediate
